hashed_password: ENC[AES256_GCM,data:8vhwkTBHw0oyYftlNfhGk4FuLp9WTw3ja/BWay3Wlv0mk7A3dL7O+XwIqXd6YxlicjcSK5/4t/fR56Mtq2m1os/8YkwhIA9OEItrYxU1i/GlK/fIxrDqlX3kyfu0w6zi7XE4iHQJHfhEow==,iv:aDtkn7GK8wQA9Ep0Q2bL4rcuC8UO0g1z/JlQJ5RkQ5s=,tag:akUiDk581Vl5glXe/9141g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ua5syascg44cznulxh7jyqddwf079yqkngp9jyawn3rafdsfuy7slnay3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1THJIeUpZbkFxS3VaOGhH
            MkVtZTl5ckU2VDdGc0Y1OU1FYWhwS1F3bGpJCkdoWXJTSFA1eG0vLytUeGVleWw4
            azRHTElLdi9PVzdudHkwWmphSU9tYU0KLS0tIFZtUStITW03S2R4UHZPZ2tJa0o1
            dVJva2xJYWZBNUxEYXNZVmdMVVNlZlEKFpeycrp5d+fW2QjlEDNQclLw8LDvENrT
            LbvkQ8uQC5qGU18DhP+8+bmC8aja8tWVgMSNrghy0t40JI5xHpI8bw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10gcmdw04ecc7q9qxhavfcns2rure4tsvvhc5cqwwghh6985e443sk7n25w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZU1tWkhoWmNqU0RpcmRr
            cDhTSlUwSGZMeHh5REsxTXFlU1BpZGk3VVF3CkpBTEFQbnQ0Q1F0Y241K0tVT3JG
            bWgvcUVPc0JLckxQNlNxVDArU1ZoSmsKLS0tIER1VnVVNjhaRjgreHRzWkZVZmhG
            Y1BGS3hVMFYyd2IyL09zRHoxVmlucXcKuIzfIikKOjJ5SB5I9TTmDHC9tmG2bFjA
            5wYyErPwDcH2b66NpIR723pNCDPXMzqS25qDwXru7m+a1ZS0kL1x/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-10T08:16:49Z"
    mac: ENC[AES256_GCM,data:+mAwld7dmNmkSxO03nffsqBlbOmxazZI9R0xtYZ+L0o/A1Eces2nvmzWcAnw4u2Zglp705dXZN71Aqg2d0Jth0r72KbT9j7rRKRoo2GaVVa3/jSj0DXqOBl28WCa+sbIhjZ3S/qC54baIeR8QRDMp06lhSTBgB0qQrB4e2L0KLI=,iv:Dhg9fiyJNcB4NvFp2c7/12jN/3kLUJ0QCZzW0F1rB5A=,tag:5BvfLPkTRJoU5tr/LTeSFw==,type:str]
    pgp:
        - created_at: "2023-03-10T08:16:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DjvWQi+AexgwSAQdAtWUKceiZvlCeF5urOhAeNxIhyh3+jr68WjJh8TpX/mQw
            NggwBloZ3686eArUTM3Pi6AlpiUppaxCGLkyo8DBGxrPJI2MdKW/Ary/0PXYh33H
            0l4BY9I0OeRXtDTdlFLXIPK1WevtDnBrAdLnzR8wSF/QbMkLSd+5PcQvZHzmBQch
            mvYrUMxrcfhBHGn1+kF3EjlKTNnBe6cY6HX4u+Wr/1CcL/W/atXze35fJLE9rM5B
            =ldr8
            -----END PGP MESSAGE-----
          fp: c5cd97e60f8f93e7b6e7309d8ef5908be01ec60c
    unencrypted_suffix: _unencrypted
    version: 3.7.3
